import { Product } from "./interfaces/Product";

export const testProducts: Product[] = [
  {
    name: "PlayStation 5",
    slug: "ps5",
    category: "Gaming",
    image: "../images/p1.jpg",
    price: 125990,
    countInStock: 12,
    brand: "Sony",
    rating: 4.7,
    reviewCount: 17,
    description:
      "A PlayStation 5 (vagy röviden PS5) a Sony által kifejlesztett és gyártott következő generációs játékkonzol, amelyet 2020 novemberében indítottak el. A PlayStation 5 sok új funkciót és fejlesztést kínál a játékosok számára.",
  },
  {
    name: "Samsung Galaxy S21",
    slug: "samsung-galaxy-s21",
    category: "Mobiltelefon",
    image: "../images/p2.jpg",
    price: 199999,
    countInStock: 25,
    brand: "Phone",
    rating: 4.8,
    reviewCount: 21,
    description:
      "A Samsung Galaxy S21 egy prémium okostelefon a Samsungtól, amely erős teljesítményt, magas minőségű kamerát és innovatív funkciókat kínál.",
  },
  {
    name: "Dell XPS 13",
    slug: "dell-xps-13",
    category: "Laptop",
    image: "../images/p3.jpg",
    price: 879000,
    countInStock: 10,
    brand: "Dell",
    rating: 3.3,
    reviewCount: 15,
    description:
      "A Dell XPS 13 egy prémium ultravékony laptop, amely erős teljesítménnyel és lenyűgöző kijelzővel rendelkezik, ideális a mobil munkához és szórakozáshoz.",
  },
  {
    name: "LG 27-inch 4K Monitor",
    slug: "lg-4k-monitor",
    category: "Monitor",
    image: "../images/p4.jpg",
    price: 215000,
    countInStock: 8,
    brand: "LG",
    rating: 4.6,
    reviewCount: 12,
    description:
      "Az LG 27-inch 4K monitor kiváló minőségű képet és nagy felbontást kínál a munka vagy szórakozás során. Ideális a videószerkesztéshez és a játékhoz.",
  },
  {
    name: "Apple iPad Pro",
    slug: "ipad-pro",
    category: "Tablet",
    image: "../images/p5.jpg",
    price: 378890,
    countInStock: 18,
    brand: "Apple",
    rating: 2.7,
    reviewCount: 14,
    description:
      "Az Apple iPad Pro egy erőteljes és sokoldalú tablet, amely alkalmas munkához és kreatív tevékenységekhez, és támogatja az Apple Pencil használatát.",
  },
  {
    name: "Bose QuietComfort 35 II",
    slug: "bose-qc35-ii",
    category: "Headphones",
    image: "../images/p6.jpg",
    price: 121490,
    countInStock: 20,
    brand: "Bose",
    rating: 3.5,
    reviewCount: 19,
    description:
      "A Bose QuietComfort 35 II egy vezeték nélküli zajszűrős fejhallgató, amely kiváló hangminőséget és kényelmet kínál, ideális utazáshoz és zenék hallgatásához.",
  },
  {
    name: "Bose QuietComfort 35 II",
    slug: "bose-qc35-ii",
    category: "Headphones",
    image: "../images/p6.jpg",
    price: 121490,
    countInStock: 20,
    brand: "Bose",
    rating: 3.5,
    reviewCount: 19,
    description:
      "A Bose QuietComfort 35 II egy vezeték nélküli zajszűrős fejhallgató, amely kiváló hangminőséget és kényelmet kínál, ideális utazáshoz és zenék hallgatásához.",
  },
  {
    name: "Bose QuietComfort 35 II",
    slug: "bose-qc35-ii",
    category: "Headphones",
    image: "../images/p6.jpg",
    price: 121490,
    countInStock: 20,
    brand: "Bose",
    rating: 3.5,
    reviewCount: 19,
    description:
      "A Bose QuietComfort 35 II egy vezeték nélküli zajszűrős fejhallgató, amely kiváló hangminőséget és kényelmet kínál, ideális utazáshoz és zenék hallgatásához.",
  },
  {
    name: "Bose QuietComfort 35 II",
    slug: "bose-qc35-ii",
    category: "Headphones",
    image: "../images/p6.jpg",
    price: 121490,
    countInStock: 20,
    brand: "Bose",
    rating: 3.5,
    reviewCount: 19,
    description:
      "A Bose QuietComfort 35 II egy vezeték nélküli zajszűrős fejhallgató, amely kiváló hangminőséget és kényelmet kínál, ideális utazáshoz és zenék hallgatásához.",
  },
  {
    name: "Bose QuietComfort 35 II",
    slug: "bose-qc35-ii",
    category: "Headphones",
    image: "../images/p6.jpg",
    price: 121490,
    countInStock: 20,
    brand: "Bose",
    rating: 3.5,
    reviewCount: 19,
    description:
      "A Bose QuietComfort 35 II egy vezeték nélküli zajszűrős fejhallgató, amely kiváló hangminőséget és kényelmet kínál, ideális utazáshoz és zenék hallgatásához.",
  },
];
